In [8]:
import pandas as pd

In [29]:
df = pd.read_csv("audible_uncleaned.csv")

<h1 style="background-color:green;padding:10px 0 10px 10px;display:inline;color:white;">About the dataset</h1>

## There are 8 total columns and 5 columns are need to clean , explain how this is possible:
#### 1) Author Column: remove Writtenby:
#### 2) Narrator Column: remove Narratedby:
#### 3) Time Column: convert hours into minutes to make it numeric
#### 4) Stars Column: from  this column create 2 separate columns that will tell stars and ratings separately
#### 5)Price Column: remove "," from it to make it numeric

In [30]:
df.head(3)

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00

In [31]:
df.columns

Index(['name', 'author', 'narrator', 'time', 'releasedate', 'language',
       'stars', 'price'],
      dtype='object')

In [32]:
df.shape

(87489, 8)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  object
 4   releasedate  87489 non-null  object
 5   language     87489 non-null  object
 6   stars        87489 non-null  object
 7   price        87489 non-null  object
dtypes: object(8)
memory usage: 5.3+ MB

<h1 style="background-color:green;padding:10px 0 10px 10px;display:inline;color:white;">Clean author,narrative,price columns</h1>

In [34]:
df["author"] = [entry.replace("Writtenby:", "") for entry in df["author"]]
df["narrator"] = [entry.replace("Narratedby:", "") for entry in df["narrator"]]
df["price"] = [entry.replace(",","") for entry in df["price"]]

In [35]:
df.head(2)

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00

<h1 style="background-color:green;padding:10px 0 10px 10px;display:inline;color:white;">Clean stars column and convert into stars and ratings</h1>

In [36]:
df["stars"] = [entry.replace("Not rated yet","0 out of 5 stars0 ratings") for entry in df["stars"]]

In [37]:
df['Stars'] = df['stars'].str.extract(r'([\d.]+) out of 5 stars')
df['Ratings'] = df['stars'].str.extract(r'(\d+) ratings')

In [38]:
df.head(56)

,name,author,narrator,time,releasedate,language,stars,price,Stars,Ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00,5,34
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,4.5,41
2,The Deep End,JeffKinney,DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,4.5,38
3,Daughter of the Deep,RickRiordan,SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,4.5,181
5,The Hunger Games: Special Edition,SuzanneCollins,TatianaMaslany,10 hrs and 35 mins,30-10-18,English,5 out of 5 stars72 ratings,656.00,5,72
6,Quest for the Diamond Sword,WinterMorgan,LukeDaniels,2 hrs and 23 mins,25-11-14,English,5 out of 5 stars11 ratings,233.00,5,11
7,The Dark Prophecy,RickRiordan,RobbieDaymond,12 hrs and 32 mins,02-05-17,English,5 out of 5 stars50 ratings,820.00,5,50
8,Merlin Mission Collection,MaryPopeOsborne,MaryPopeOsborne,10 hrs and 56 mins,02-05-17,English,5 out of 5 stars5 ratings,1256.00,5,5
9,The Tyrant’s Tomb,RickRiordan,RobbieDaymond,13 hrs and 22 mins,24-09-19,English,5 out of 5 stars58 ratings,820.00,5,58
10,"The Titan's Curse: Percy Jackson, Book 3",RickRiordan,JesseBernstein,8 hrs and 48 mins,14-01-10,English,4.5 out of 5 stars130 ratings,820.00,4.5,130
11,Magic Tree House Collection: Books 9-16,MaryPopeOsborne,MaryPopeOsborne,5 hrs and 23 mins,24-08-11,English,5 out of 5 stars6 ratings,1206.00,5,6
12,Magic Tree House Collection: Books 1-8,MaryPopeOsborne,MaryPopeOsborne,6 hrs and 1 min,27-09-11,English,5 out of 5 stars7 ratings,1206.00,5,7
13,Magnus Chase and the Ship of the Dead,RickRiordan,MichaelCrouch,12 hrs and 58 mins,03-10-17,English,5 out of 5 stars41 ratings,820.00,5,41
14,Northern Lights,PhilipPullman,"PhilipPullman,fullcast,RuthWilson",11 hrs and 55 mins,24-06-21,English,4 out of 5 stars2 ratings,1093.00,4,2
15,Geronimo Stilton #13 and #14,GeronimoStilton,BillLobley,2 hrs and 25 mins,08-02-08,English,4.5 out of 5 stars33 ratings,467.00,4.5,33
16,Magic Tree House Collection,MaryPopeOsborne,MaryPopeOsborne,5 hrs and 4 mins,26-12-04,English,5 out of 5 stars7 ratings,1206.00,5,7
17,Exile,ShannonMessenger,CaitlinKelly,14 hrs and 41 mins,06-11-18,English,5 out of 5 stars20 ratings,836.00,5,20
18,Merlin Mission Collection,MaryPopeOsborne,MaryPopeOsborne,10 hrs and 18 mins,02-05-17,English,5 out of 5 stars11 ratings,1256.00,5,11
19,Neverseen,ShannonMessenger,CaitlinKelly,16 hrs and 42 mins,06-11-18,English,5 out of 5 stars13 ratings,1003.00,5,13
20,The Tower of Nero,RickRiordan,RobbieDaymond,12 hrs and 12 mins,06-10-20,English,5 out of 5 stars79 ratings,615.00,5,79
21,"Eldest: The Inheritance Cycle, Book 2",ChristopherPaolini,GerrardDoyle,23 hrs and 29 mins,14-04-09,English,4.5 out of 5 stars47 ratings,957.00,4.5,47
22,Artemis Fowl,EoinColfer,GerryO'Brien,6 hrs and 46 mins,11-04-13,English,5 out of 5 stars27 ratings,683.00,5,27
23,Geronimo Stilton 22 & 24,GeronimoStilton,BillLobley,2 hrs and 37 mins,01-02-11,English,4.5 out of 5 stars25 ratings,469.00,4.5,25
24,Percy Jackson and the Battle of the Labyrinth,RickRiordan,JesseBernstein,10 hrs and 32 mins,21-01-10,English,5 out of 5 stars101 ratings,820.00,5,101
25,Winnie-the-Pooh,A.A.Milne,PeterDennis,2 hrs and 46 mins,28-12-03,English,5 out of 5 stars15 ratings,468.00,5,15
26,Magic Tree House Collection: Books 25-32,MaryPopeOsborne,MaryPopeOsborne,7 hrs and 9 mins,01-09-20,English,5 out of 5 stars3 ratings,1256.00,5,3
27,Geronimo Stilton #20 and #21,GeronimoStilton,BillLobley,2 hrs and 32 mins,01-10-10,English,5 out of 5 stars18 ratings,469.00,5,18
28,The Red Pyramid,RickRiordan,"JaneCollingwood,JosephMay",13 hrs and 44 mins,24-01-13,English,4.5 out of 5 stars37 ratings,820.00,4.5,37
29,Mystery of the Griefer's Mark,WinterMorgan,LukeDaniels,1 hr and 53 mins,25-11-14,English,5 out of 5 stars9 ratings,233.00,5,9
30,Geronimo Stilton #17,GeronimoStilton,BillLobley,2 hrs and 28 mins,13-07-09,English,5 out of 5 stars8 ratings,468.00,5,8
31,The House at Pooh Corner,A.A.Milne,PeterDennis,3 hrs and 12 mins,05-04-05,English,5 out of 5 stars5 ratings,374.00,5,5
32,Mission Unstoppable,DanGutman,MichaelGoldstrom,6 hrs and 8 mins,01-08-13,English,5 out of 5 stars8 ratings,702.00,5,8
33,Darkness of Dragons,TuiT.Sutherland,ShannonMcManus,10 hrs and 26 mins,01-08-17,English,5 out of 5 stars8 ratings,656.00,5,8
34,"14 Short Stories Bundle for Kids: Adventure, S...",NayomiPhillips,"MonicaRachelle,JimD.Johnston,KatieOtten",3 hrs and 13 mins,22-01-19,English,0 out of 5 stars0 ratings,501.00,0,0
35,The Adventures of Rusty,RuskinBond,NehaGargava,5 hrs and 41 mins,01-11-18,Hindi,4.5 out of 5 stars10 ratings,284.00,4.5,10
36,Geronimo Stilton #15 and #16,GeronimoStilton,BillLobley,2 hrs and 43 mins,08-02-08,English,4 out of 5 stars28 ratings,467.00,4,28
37,The Lost Heir,TuiT.Sutherland,ShannonMcManus,7 hrs and 23 mins,04-02-16,English,5 out of 5 stars9 ratings,575.00,5,9
38,Everblaze,ShannonMessenger,CaitlinKelly,14 hrs and 39 mins,06-11-18,English,5 out of 5 stars18 ratings,836.00,5,18
39,Treasure Hunters in Trouble,WinterMorgan,LukeDaniels,1 hr and 58 mins,31-03-15,English,5 out of 5 stars7 ratings,668.00,5,7
40,Lodestar,ShannonMessenger,CaitlinKelly,16 hrs and 31 mins,06-11-18,English,5 out of 5 stars19 ratings,1003.00,5,19
41,Curse of the Arctic Star,CarolynKeene,JorjeanaMarie,3 hrs and 35 mins,28-12-14,English,4.5 out of 5 stars25 ratings,305.00,4.5,25
42,The Ghost of Grey Fox Inn,CarolynKeene,JorjeanaMarie,3 hrs and 19 mins,20-03-17,English,5 out of 5 stars11 ratings,305.00,5,11
43,Rowley Jefferson's Awesome Friendly Adventure,JeffKinney,ChristopherGebauer,1 hr and 31 mins,04-08-20,English,4 out of 5 stars16 ratings,410.00,4,16
44,Flashback,ShannonMessenger,CaitlinKelly,23 hrs and 9 mins,11-12-18,English,5 out of 5 stars12 ratings,1170.00,5,12
45,Secret of the Red Arrow,FranklinW.Dixon,TimGregory,3 hrs and 33 mins,04-11-15,English,4.5 out of 5 stars16 ratings,305.00,4.5,16
46,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,WalterLewis,3 hrs and 51 mins,13-01-10,English,4 out of 5 stars4 ratings,615.00,4,4
47,Clash of the Creepers,WinterMorgan,LukeDaniels,2 hrs and 1 min,07-07-15,English,5 out of 5 stars10 ratings,233.00,5,10
48,The Skeletons Strike Back,WinterMorgan,LukeDaniels,2 hrs and 1 min,07-07-15,English,5 out of 5 stars7 ratings,233.00,5,7
49,Dragonslayer,TuiT.Sutherland,ShannonMcManus,12 hrs and 44 mins,03-03-20,English,5 out of 5 stars17 ratings,656.00,5,17
50,A Bear Called Paddington,MichaelBond,StephenFry,2 hrs and 39 mins,24-06-08,English,0 out of 5 stars0 ratings,266.00,0,0
51,Gregor and the Curse of the Warmbloods,SuzanneCollins,PaulBoehmer,7 hrs and 47 mins,26-12-04,English,0 out of 5 stars0 ratings,1005.00,0,0
52,The Dark Secret,TuiT.Sutherland,ShannonMcManus,7 hrs and 35 mins,01-07-16,English,5 out of 5 stars9 ratings,575.00,5,9
53,The Gruffalo's Child,"JuliaDonaldson,AxelScheffler",ImeldaStaunton,22 mins,19-08-10,English,4.5 out of 5 stars4 ratings,323.00,4.5,4
54,Merlin Mission Collection,MaryPopeOsborne,MaryPopeOsborne,13 hrs and 24 mins,02-05-17,English,5 out of 5 stars8 ratings,1256.00,5,8
55,Keys to the Demon Prison,BrandonMull,E.B.Stevens,17 hrs and 37 mins,01-08-13,English,5 out of 5 stars1 rating,516.00,5,NaN

In [39]:
df.drop("stars",axis=1,inplace=True)

In [40]:
df.head(2)

,name,author,narrator,time,releasedate,language,price,Stars,Ratings
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,2 hrs and 20 mins,04-08-08,English,468.00,5,34
1,The Burning Maze,RickRiordan,RobbieDaymond,13 hrs and 8 mins,01-05-18,English,820.00,4.5,41

<h1 style="background-color:green;padding:10px 0 10px 10px;display:inline;color:white;">Clean Time column</h1>

In [41]:
import pandas as pd
import re

# Define a function to extract minutes from a string
def extract_minutes(time_str):
    # Use regular expressions to extract hours and minutes
    pattern = re.search(r'(\d+) hrs and (\d+) mins',time_str)    
    hours_match = re.search(r'(\d+) hrs', time_str)
    minutes_match = re.search(r'(\d+) mins', time_str)

    total_minutes = 0
    
    if pattern:
        hours = int(pattern.group(1))
        minutes = int(pattern.group(2))
        total_minutes = (hours * 60) + minutes
        return total_minutes
    elif hours_match:
        total_minutes += int(hours_match.group(1)) * 60
        return total_minutes
    elif minutes_match:
        total_minutes += int(minutes_match.group(1))
        return total_minutes
    else:
        # If the format doesn't match, consider it as 0 minutes
        return 0
        

# Apply the extract_minutes function to the 'TimeColumn' and create a new column 'Minutes'
df['Minutes'] = df['time'].apply(extract_minutes)

In [42]:
df.drop("time",axis=1,inplace=True)

In [43]:
df.head(3)

,name,author,narrator,releasedate,language,price,Stars,Ratings,Minutes
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,04-08-08,English,468.00,5,34,140
1,The Burning Maze,RickRiordan,RobbieDaymond,01-05-18,English,820.00,4.5,41,788
2,The Deep End,JeffKinney,DanRussell,06-11-20,English,410.00,4.5,38,123

### Write this cleaned code into separate csv file

In [45]:
df.to_csv("new_audible_cleaned_dataset.csv",index=False)